### ISSUE TITLE
Visual preview on client

### ISSUE THREAD

**Issue by Madis0** [JustAlittleWolf/ModDetectionPreventer#3]
I think the ideal fix would be to resolve it visually on client but when the server somehow receives it back, the client sends the original string ID.

Would it be feasible to achieve this?

**Comment by JustAlittleWolf** [comment]
I am not entirely sure what you are asking here.

The client already visually resolves the keybinds on signs, doesn't send this to the server. It is only when you edit a sign that the client replaces all the keybind Text-Objects with the corresponding string values, so that you can edit the text without issues (there is no UI for editing text-objects).

**Comment by Madis0** [comment]
I was asking if the mod could prevent that 
> client replaces all the keybind Text-Objects with the corresponding string values

but I'm gonna ask Mojang as well if they'd want to fix it.

**Comment by JustAlittleWolf** [comment]
This would require a new way to edit the text on signs (like the mod [Text Utilities](https://modrinth.com/mod/text-utilities), as Text-Objects are not simply just strings on the sign. This would be beyond the scope of this project, as I only want to provide a solution to the problem itself.

**Comment by Madis0** [comment]
The idea was to just ignore the objects rather than edit them, but I do understand that this can be complex to implement and prone to breakage.
