### ISSUE TITLE
How does the test world work?

### ISSUE THREAD

**Issue by Madis0** [JustAlittleWolf/ModDetectionPreventer#5]
I tried replicating the signs by doing a setblock sign which has a translation string, but I am unable to edit that side of the sign on both creative and survival. So what did you change to make it editable?

**Comment by JustAlittleWolf** [comment]
Hm that is weird. I remember having had the same issue when I experimented around with signs for the first time, but now I am unable to recreate that. Do you have another mod installed, that might mess with signs?

**Comment by Madis0** [comment]
No.
1. Create a vanilla 1.20.4 instance
2. Create a new world
3. Run `/setblock ~ ~ ~ oak_sign{front_text:{messages:['{"translate":"gui.cancel"}','{"text":""}','{"text":""}','{"text":""}']}} replace` 
4. Try editing that side of the sign in survival or creative.

Maybe your test world is older than 1.20, where [this bug was supposed to be fixed](https://www.minecraft.net/en-us/article/minecraft-snapshot-23w14a)?

> Signs with non-text chat components can no longer be edited

**Comment by JustAlittleWolf** [comment]
Oh, turns out you need to have a static text component on the same line as the keybind, or translatable as well. So your command would look like
`/setblock ~ ~ ~ oak_sign{front_text:{messages:['[{"text":" "},{"translate":"gui.cancel"}]','{"text":""}','{"text":""}','{"text":""}']}} replace`

(In this example I added an empty space before the translation component)

**Comment by Madis0** [comment]
Right, now I can confirm it.
